### ISSUE TITLE
No sample file provided

### ISSUE THREAD

**Issue by adoussot** [dlebrero/wireshark-plantuml#1]
Thanks for this really useful project! However since I'm not really used to clojure I didn't manage to create a correct uml graph from a wireshark json sample about my connexion to gitlab (with filter: `(ip.src==52.167.219.168||ip.dst==52.167.219.168)`). 

- Is it possible to provide a sample json test (without providing sensitive informations)  ?
    + to check if the program is correctly working on my computer. 
    + to better understand the process realize

**Comment by dlebrero** [comment]
Hi Alexis,

I will try to upload a sample this weekend.

Thanks for the interest,

Dan

**Comment by adoussot** [comment]
Thanks !

**Comment by dlebrero** [comment]
Uploaded a sample.json file. Let me know how it goes.

Regards,

Dan

**Comment by adoussot** [comment]
Thank you very much Dan, this work smoothly! 
Regards
alexis
